# Generated by Django 4.1.3 on 2022-11-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vertrieb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firmenname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='auszubildende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=45)),
                ('Nachname', models.CharField(max_length=100)),
                ('Alter', models.IntegerField(null=True)),
                ('Stadt', models.CharField(max_length=100)),
                ('Geschlecht', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Submission_date', models.DateTimeField()),
                ('Ausbildung', models.CharField(max_length=150)),
                ('Beziehung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzlet.vertrieb')),
            ],
        ),
    ]
